name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    # Ensure the secrets are correctly accessed
    - name: Create GoogleService-Info.plist
      run: echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > ios/GoogleService-Info.plist

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Archive iOS
      run: |
        xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/Runner.xcarchive \
          clean archive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/Runner.xcarchive \
          -exportOptionsPlist ios/Runner/ExportOptions.plist \
          -exportPath $PWD/build/ios/ipa

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: build/ios/ipa/*.ipa

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    - name: Deploy to Firebase App Distribution
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json
        echo "Deploying to Firebase App Distribution"
        firebase appdistribution:distribute build/ios/ipa/*.ipa \
          --app 1:204969236584:ios:3ba1b6ffce11e586e283dd \
          --release-notes "Automated build from GitHub Actions" \
          --groups v1.0